parameters:
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

services:
    gherkin:
        class: App\MainBundle\Services\GherkinService
        arguments: [@service_container]
    mink:
        class: App\MainBundle\Services\MinkService
        arguments: [@service_container]
    test_set_execution:
        class: App\MainBundle\Services\TestSetExecutionService
        arguments: [@gherkin, @slugify]
