parameters:
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

services:
    gherkin:
        class: App\MainBundle\Services\GherkinService
        arguments: [@service_container]
    mink:
        class: App\MainBundle\Services\MinkService
        arguments: [@service_container]
    test_set_execution:
        class: App\MainBundle\Services\TestSetExecutionService
        arguments: [@doctrine.orm.entity_manager, @gherkin, @slugify]
    appmain.form_extention.form_icon:
        class: App\MainBundle\Form\Extension\FieldTypeIconExtension
        tags:
            - { name: form.type_extension, alias: form }
    test_set_run_manager:
        class: App\MainBundle\Services\TestSetRunService
        arguments: [@doctrine.orm.entity_manager]
